Books-Inventory-master/Assignment/Assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from .router import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('googlebooks/', include('googlebooks.urls')),
    path('api/', include(router.urls))
]

Books-Inventory-master/Assignment/googlebooks/urls.py
from django.urls import path

from . import views

app_name= 'googlebooks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inventory', views.InventoryView.as_view(), name= 'inventory'),
    path('<str:ID>/edit', views.BooksUpdate.as_view(), name='books_edit'),
    path('<str:ID>/delete', views.BooksDelete.as_view(), name= 'books_delete'),
    path('add', views.BooksAdd.as_view(), name='books_add')
]

Books-Inventory-master/Assignment/googlebooks/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Books(models.Model):
	book_name=models.CharField(max_length=200)
	ID= models.CharField(max_length=200, primary_key= True, default= "" )
	created_at =  models.DateTimeField(auto_now_add= True)
	preview_link=models.URLField(max_length=200)
	count= models.IntegerField(default=0)
	def __str__(self):
		return self.book_name
	


#class Detail(models.Model):
#	book= models.ForeignKey(Books, on_delete=models.CASCADE)
#	count= models.IntegerField(default=0)

#	 def __str__(self):
 #       return self.book

Books-Inventory-master/Assignment/googlebooks/forms.py
from django import forms
from .models import Books


class SearchForm(forms.Form):
	search= forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'search for a book'
		}
	)) 

class UpdateForm(forms.Form):
	title=forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'Enter Title'
		}
	)) 
	previewLink=forms.URLField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'Google books Link'
		}
	)) 
	ID= forms.CharField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'must be google book id'
		}
	)) 
	copies=forms.IntegerField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'how many copies you want to add'
		}
	)) 

class AddForm(forms.Form):
	url= forms.URLField(widget=forms.TextInput(
		attrs={
			'class': 'form-control',
			'placeholder': 'url of the google book'
		}
	)) 
		

Books-Inventory-master/Assignment/googlebooks/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.http import HttpResponse
from .models import Books
from .forms import SearchForm, UpdateForm, AddForm
from .book_search import gbooks
import re, json, requests
from django.utils import timezone
from .base_script import start1
import os


class IndexView(TemplateView):
	template_name='googlebooks/home.html'

	def get(self, request):
		search_form= SearchForm
		#start1()

		return render(request, self.template_name, {'searchform': search_form})

	def post(self, request):
		searchform= SearchForm(request.POST)
		if searchform.is_valid():
			volume= searchform.cleaned_data['search']
		a= gbooks(volume)
		b= a.search()
		try:
			if (b[0]==[]):
				return HttpResponse("No Books Found", status= 401)
		except:
			return render(request, 'googlebooks/search.html', {'b':b})

		




class InventoryView(ListView):
	model= Books
	template_name='googlebooks/inventory.html'
	

	def get(self, request):
		books=Books.objects.all()
		print (books)
		
		return render(request, self.template_name, {'books': books})

class BooksUpdate(TemplateView):
	def get(self, request, ID):
		form=UpdateForm
		return render(request, 'googlebooks/update.html', {'form':form})
	def post(self, request, ID):
		updateform= UpdateForm(request.POST)
		if updateform.is_valid():
			title=updateform.cleaned_data['title']
			preview_link=updateform.cleaned_data['previewLink']
			key=updateform.cleaned_data['ID']
			copies=updateform.cleaned_data['copies']

			q=Books.objects.filter(ID=ID)
			q.book_name=title
			q.preview_link=preview_link
			q.ID=key
			q.count=copies
			q.save()
		books= Books.objects.all()
		return render(request, 'googlebooks/inventory', {'books': books})


class BooksDelete(TemplateView):
	
	def get(self, request, ID):
		q=Books.objects.get(ID=ID)
		q.delete()
		books=Books.objects.all()
		return render(request, 'googlebooks/inventory.html', {'books': books})

class BooksAdd(TemplateView):
	def get(self, request):
		addform= AddForm
		return render(request, 'googlebooks/add.html', {'form':addform})

	def post(self, request):
		addform= AddForm(request.POST)
		if addform.is_valid():
			url=addform.cleaned_data['url']
			key=re.findall("id=.+?[&]", url)
			temp_key=key[0][3:-1]
		googleapikey=os.environ.get('API_KEY')
		book_url="https://www.googleapis.com/books/v1/volumes/{}".format(temp_key)
		r = requests.get(url=book_url, params={'key':googleapikey})
		my_json= r.json()
		p_link="https://books.google.co.in/books?id={}".format(temp_key)
		q=Books(book_name=my_json['volumeInfo']['title'], ID=temp_key, preview_link='p_link', created_at= timezone.now())
		q.save()
		books=Books.objects.all()
		return render(request, 'googlebooks/inventory.html', {'books':books})

Books-Inventory-master/Assignment/googlebooks/templates/googlebooks/add.html
<div class="container">

					<form method="post">

						{% csrf_token %}
						{{ form.errors }}
						<div id="index_form">
							{{ form.as_p }}
							<button type="submit" class="btn btn-outline-info">submit</button>
						</div>
					</form>
			</div>

Books-Inventory-master/Assignment/googlebooks/templates/googlebooks/home.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<title>{{ Books }}</title>
		<meta charset="UTF-8">
	 	<meta name="viewport" content="width=device-width, initial-scale=1">
	   <link rel="stylesheet" type="text/css" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
	   <link href="https://fonts.googleapis.com/css?family=Rock Salt" rel='stylesheet'>
	  </head>
	<body>
		<div class="container">

					<form method="post">

						{% csrf_token %}
						{{ searchform.errors }}
						<div id="index_form">
							{{ searchform.as_p }}
							<button type="submit" class="btn btn-outline-info">submit</button>
						</div>
					</form>
			</div>
			<a class= "inventory" href="{% url 'googlebooks:inventory' %}">Inventory</a>
	</body>		
</html>

Books-Inventory-master/Assignment/googlebooks/templates/googlebooks/inventory.html
<h1>Inventory</h1>
<ul>

	{% for book in books %}
		<li><a href="{{ book.preview_link }}">{{ book.book_name }}</a>
			<a href="{% url 'googlebooks:books_edit' book.ID %}">edit</a>
			<a href="{% url 'googlebooks:books_delete' book.ID %}">delete</a>
		</li>
	{% endfor %}
</ul>

<a href=" {% url 'googlebooks:books_add' %}">Add</a>

Books-Inventory-master/Assignment/googlebooks/templates/googlebooks/search.html
{% for item in b %}
	<ul>
		<img src="{{ item.2 }}"></img><a id="title" class="title" href="{{ item.1 }}">{{ item.0 }}</a>
		<i> {{ item.3 }} </i>
	</ul>
{% endfor %}

Books-Inventory-master/Assignment/googlebooks/templates/googlebooks/update.html
<h1>EDIT</h1>
<div class="container">

					<form method="post">

						{% csrf_token %}
						{{ form.errors }}
						<div id="index_form">
							{{ form.as_p }}
							<button type="submit" class="btn btn-outline-info">submit</button>
						</div>
					</form>
			</div>